export const SAAM_BRANCHES = [
    "Santos",
    "Itaguaí",
    "Rio",
    "Angra",
    "Vitória",
    "Salvador",
    "Suape",
    "Pecém",
    "São Luís (Itaqui)",
    "Belém",
    "Paranaguá",
    "São Francisco do Sul",
    "Itajaí",
    "Imbituba",
    "Rio Grande",
    "Santana (Macapá)"
];

export const FLEET_VESSELS = [
    { vessel: "SAAM CANINDÉ", imo: "9457414", mmsi: "710012010", year: 2009, designClass: "RA 3.000 - DETROIT", classeApelido: "Classe 3.000 - C" },
    { vessel: "SAAM CRAÓ", imo: "9457438", mmsi: "710005670", year: 2009, designClass: "RA 3.000 - DETROIT", classeApelido: "Classe 3.000 - C" },
    { vessel: "SAAM CHARRUA", imo: "9457440", mmsi: "710001780", year: 2009, designClass: "RA 3.000 - DETROIT", classeApelido: "Classe 3.000 - C" },
    { vessel: "SAAM CAIAPÓ", imo: "9457426", mmsi: "710011790", year: 2009, designClass: "RA 3.000 - DETROIT", classeApelido: "Classe 3.000 - C" },
    { vessel: "SAAM CARAJÁ", imo: "9457488", mmsi: "710012030", year: 2009, designClass: "RA 3.000 - DETROIT", classeApelido: "Classe 3.000 - C" },
    { vessel: "SAAM CARIPUNA", imo: "9457476", mmsi: "710012020", year: 2009, designClass: "RA 3.000 - DETROIT", classeApelido: "Classe 3.000 - C" },
    { vessel: "SAAM ÁGUIA", imo: "9946207", mmsi: "710033460", year: 2022, designClass: "DB 3280 E - Escort Tug", classeApelido: "Classe 80 MTU" },
    { vessel: "SAAM ALTAIR", imo: "9718272", mmsi: "710018470", year: 2014, designClass: "DB 3270 - DETROIT", classeApelido: "Classe 70 MTU" },
    { vessel: "SAAM MIRA", imo: "9876763", mmsi: "710033360", year: 2019, designClass: "DB 3280 - Escort Tug", classeApelido: "Classe 80 CAT" },
    { vessel: "SAAM TIAKI", imo: "9876854", mmsi: "710033380", year: 2020, designClass: "DB 3280 - Escort Tug", classeApelido: "Classe 80 CAT" },
    { vessel: "SAAM ALYA", imo: null, mmsi: null, year: null, designClass: "DB 3280 - Escort Tug", classeApelido: "Classe 80 CAT" },
    { vessel: "SAAM ALPHA", imo: null, mmsi: null, year: null, designClass: "DB 3280 - Escort Tug", classeApelido: "Classe 80 CAT" },
    { vessel: "SAAM CRUX", imo: null, mmsi: null, year: null, designClass: "DB 3280 - Escort Tug", classeApelido: "Classe 80 CAT" },
    { vessel: "SAAM ELECTRA", imo: null, mmsi: null, year: null, designClass: "DB 3280 - Escort Tug", classeApelido: "Classe 80 CAT" },
    { vessel: "HUGO", imo: "9685578", mmsi: "710014960", year: null, designClass: "RA 3.000 - INACE FIFI", classeApelido: "Classe 3.000 - INACE FIFI" },
    { vessel: "PHILLIPE", imo: "9685566", mmsi: "710014280", year: null, designClass: "RA 3.000 - INACE FIFI", classeApelido: "Classe 3.000 - INACE FIFI" },
    { vessel: "ALCANTARA", imo: null, mmsi: null, year: null, designClass: null, classeApelido: null },
    { vessel: "BRUCUTU", imo: null, mmsi: null, year: null, designClass: null, classeApelido: null },
    { vessel: "TIMBOPEBA", imo: null, mmsi: null, year: null, designClass: null, classeApelido: null },
    { vessel: "C. CAILLEAN", imo: null, mmsi: null, year: null, designClass: null, classeApelido: null },
    { vessel: "C. SAGITARIUS", imo: null, mmsi: null, year: null, designClass: null, classeApelido: null },
    { vessel: "C. SIRIUS", imo: null, mmsi: null, year: null, designClass: null, classeApelido: null },
    { vessel: "C. SULIS", imo: null, mmsi: null, year: null, designClass: null, classeApelido: null },
    { vessel: "TAPAJÓ", imo: null, mmsi: null, year: null, designClass: "RA 2.500 - DETROIT", classeApelido: "Classe 2.500 - T" },
    { vessel: "TAPEBA", imo: null, mmsi: null, year: null, designClass: "RA 2.500 - DETROIT", classeApelido: "Classe 2.500 - T" },
    { vessel: "TARIANA", imo: null, mmsi: null, year: null, designClass: "RA 2.500 - DETROIT", classeApelido: "Classe 2.500 - T" },
    { vessel: "TERENA", imo: null, mmsi: null, year: null, designClass: "RA 2.500 - DETROIT", classeApelido: "Classe 2.500 - T" },
    { vessel: "TICUNA", imo: null, mmsi: null, year: null, designClass: "RA 2.500 - DETROIT", classeApelido: "Classe 2.500 - T" },
    { vessel: "PAITER", imo: null, mmsi: null, year: null, designClass: "RA 2.500 - KEPPEL", classeApelido: "Classe 2.500 - P" },
    { vessel: "PANARÁ", imo: null, mmsi: null, year: null, designClass: "RA 2.500 - KEPPEL", classeApelido: "Classe 2.500 - P" },
    { vessel: "PARECI", imo: null, mmsi: null, year: null, designClass: "RA 2.500 - KEPPEL", classeApelido: "Classe 2.500 - P" },
    { vessel: "PARINTINS", imo: null, mmsi: null, year: null, designClass: "RA 2.500 - KEPPEL", classeApelido: "Classe 2.500 - P" }
];
